################################################################################
###                           Yazi User Keybindings                          ###
################################################################################

# Square brackets ("[" and "]") create a sequence
# Non-regular keys use angle brckets ("<" and ">")
# "<S-a>" represents Shift+a
# "<C-a>" represents Ctrl+a
# "<A-a>" represents Alt+a
# Most non-regular keys use their full names:
#   Home, End, PageUp, PageDown, Up, Down, Left, Right
#   Backspace, Delete, Enter, Space, Tab, Esc
#   F1, F2, ...

[manager]
prepend_keymap = [
  {on = ['<C-t>'    ], run = ['shell "$SHELL" --block --confirm'], desc = 'Open shell here'                                 },
  {on = ['q'        ], run = ['close'                           ], desc = 'Close the current tab, or quit if it is last tab'},
  {on = ['<A-Up>'   ], run = ['seek -1'                         ], desc = 'Seek up 1 unit in the preview'                   },
  {on = ['<A-Down>' ], run = ['seek 1'                          ], desc = 'Seek down 1 unit in the preview'                 },
  {on = ['<Home>'   ], run = ['arrow -99999999'                 ], desc = 'Move cursor to the top'                          },
  {on = ['<End>'    ], run = ['arrow 99999999'                  ], desc = 'Move cursor to the bottom'                       },
  {on = ['<Tab>'    ], run = ['select --state=none', 'arrow 1'  ], desc = 'Toggle the current selection state'              },
  {on = ['<F2>'     ], run = ['rename --cursor=before_ext'      ], desc = 'Rename selected file(s)'                         },
  {on = ['<Delete>' ], run = ['remove'                          ], desc = 'Trash selected file(s)'                          },
  {on = ['<F4>'     ], run = ['plugin --sync hide-preview'      ], desc = 'Hide or show preview'                            },
  {on = ['<F3>'     ], run = ['plugin --sync max-preview'       ], desc = 'Maximize or restore preview'                     },
]

[input]
prepend_keymap = [
  {on = ['<Esc>'], run = 'close', desc = 'Cancel input'},
]


